site_name: C# alapok
site_author: Benedek Zoltán
copyright: Copyright &copy; Benedek Zoltán
repo_name: bzolka/CSharp
repo_url: https://github.com/bzolka/CSharp

theme:
  name: material
  custom_dir: theme-overrides
  language: hu
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - tabs
    - navigation.expand

extra_css:
  - extra-material-theme.css

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search:
      prebuild_index: true

nav:
  - index.md
  - Stringek:
      - StringAlapgyakorlatok/string-alapok-feladatcsoport-1.md
  - 'Objektumok létrehozása':
      - Konstruktor:
          - ObjektumokLetrehozasa/Konstruktor/konstruktor-alapok.md
      - Inicializálás:
          - ObjektumokLetrehozasa/Inicializalas/inicializalas-alapok.md        
          - ObjektumokLetrehozasa/Inicializalas/inicializalas-feladatok.md
  - 'Statikus tagok':
      - Static/static.md
      - Static/static-feladatok.md
  - Linq:
      - Linq/Linq-attekinto.md
      - Linq/Linq-kiskerdesek.md
      - Linq/Linq-csoportositas-feladatok.md